services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:

#? Useful commands:
#? Start the containers in the background:
#?  docker-compose up -d
#? Stop and remove containers (does not delete volumes):
#?  docker-compose down